networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:

services:
  traefik:
    image: "traefik:v3.5.2"
    # traefik config
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  orderservice:
    container_name: orderservice
    build: .
    command: [ "/app/ordersystem" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orders.entrypoints=web"
      - "--entryPoints.web.address=:3000"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
      - DB_HOST=order-postgres
      - PGSSLMODE=disable
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    volumes:
      - ./frontend:/public
    environment:
      - SERVER_ROOT=/public
      - SERVER_LOG_LEVEL=debug
      - SERVER_PORT=80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.routers.website.rule=Host(`localhost`)"
      - "traefik.http.routers.website.priority=1"
      - "traefik.http.services.website.loadbalancer.server.port=80"
    networks:
      - web

  order-postgres:
    image: postgres:18
    restart: always
    networks:
      - intercom
    volumes:
      - order_pg_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432